### ISSUE TITLE
Middlewares in route components are never run

### ISSUE THREAD

**Issue by cslee** [universal-vue/examples#11]
Middlewares defined in route components are never run

E.g. in the NotFound view:

https://github.com/universal-vue/examples/blob/74a532b318e04bb7e84a0d5e1297e5a5ac3781c6/src/views/NotFound.vue#L18-L28

And it's not mentioned in the Universal Vue doc that middlewares can be defined in a component. Could you please clarify whether the example here is incorrect? Thanks.

**Comment by phil294** [comment]
I got confused by this, too. Even the official example demo (this repo, basically) does not return 404 in its 404 component. https://uvue.yabab.net/not-found

It would be helpful to know how one would set up response status codes.

**Comment by chymz** [comment]
You are right, first versions of UVue supports middlewares directly in components, but this feature has been removed. I'll fix this repo
