### ISSUE TITLE
[@uvue/server] UnhandledPromiseRejectionWarning: ReferenceError: server is not defined

### ISSUE THREAD

**Issue by Lord-Y** [universal-vue/examples#9]
If you add in `./src/plugins/proxy.js` this content:
```
const { createProxyMiddleware } = require("http-proxy-middleware");

export default {
  install(app) {
    const proxyOptions = {
      target: "https://xxxxxx.xxx",
      changeOrigin: true
    };
    app.use("/api/v1/", createProxyMiddleware(proxyOptions));
  }
};
```

Add into `server.config.js` this content:
```
...
...
    // Serve static files
    '@uvue/server/plugins/static',
    // API
    './src/server/apiPlugin',
    './src/server/proxy'
  ],
  // Watch for changes in these files to automatically reboot server
  watch: ['src/server/**/*.js'],
  // SPA paths: no SSR occur for these paths
  spaPaths: ['/spa'],
};

```
Build your docker image and after run it, it will faild this error:
`(node:1) UnhandledPromiseRejectionWarning: ReferenceError: server is not defined
    at catch.err (/home/node/app/node_modules/@uvue/server/start.js:105:3)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`
As explicitely said the problem is coming from `node_modules/@uvue/server/start.js:105:3` and we can see that server is clearly undefined into the catch block.

**Comment by chymz** [comment]
Nice catch, I'll fix this
